In [1]:
import os
import sys

In [2]:
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [3]:
sys.path.append("../../deep-learning-dna")
sys.path.append("../../settransformer")

In [4]:
import settransformer as stf

In [5]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import display
import math
import string

import settransformer as stf
from common.models import dnabert
from common import dna
from lmdbm import Lmdb
from common.data import DnaSequenceGenerator, DnaLabelType, DnaSampleGenerator, find_dbs
import wandb

import tf_utils as tfu

In [6]:
strategy = tfu.strategy.cpu()

---
# Load Data

In [7]:
#Import pretrained model
api = wandb.Api()
model_path = api.artifact("sirdavidludwig/deep-learning-dna/dnabert-pretrain-ablation-dim:8dim").download()
pretrained_model = dnabert.DnaBertModel.load(model_path)
pretrained_model

In [8]:
#Load datafiles
dataset_path = api.artifact("sirdavidludwig/nachusa-dna/dnasamples:latest").download()
samples = find_dbs(dataset_path + '/train')
samples[0]

wandb: Downloading large artifact dnasamples:latest, 4086.55MB. 1260 files... Done. 0:3:14.4


'./artifacts/dnasamples:v1/train/WS-AG-Apr2016_S85_L001_R1_001.db'

In [187]:
max_files = 1260

---
# Create Dataset

In [9]:
#Generate batches
subsample_length = 700
sequence_length = 150
kmer = 3
batch_size = 20
batches_per_epoch = 128
augument = True
labels = DnaLabelType.SampleIds
dataset = DnaSampleGenerator(samples=samples, subsample_length = subsample_length, sequence_length=sequence_length,kmer=kmer,batch_size=batch_size,batches_per_epoch=batches_per_epoch,augment=augument,labels=labels)

In [ ]:
dataset[5][1]

In [12]:
dataset[0][0].shape

(20, 700, 148)

In [13]:
dataset[0][0][0].shape

(700, 148)

In [14]:
dataset[0][0][0][0].shape

(148,)

---
# Create Embeddings

In [15]:
#Create 8 dimensional embeddings
pretrained_encoder= dnabert.DnaBertEncoderModel(pretrained_model.base)
pretrained_encoder.trainable = False

In [16]:
embeddings = pretrained_encoder.predict(dataset[0][0][0])

In [17]:
embeddings.shape

(700, 8)

In [18]:
embeddings

array([[ -6.9496713 ,   1.6210482 ,  -7.8239136 , ...,  -4.2330317 ,
         -1.5559857 ,  -3.900096  ],
       [ -8.390611  ,   1.6148111 ,  -4.0261803 , ...,  -8.997752  ,
          1.2903745 ,   2.3432248 ],
       [ -4.8556437 ,   2.844587  ,  -5.9141846 , ...,  -8.047518  ,
          2.4954636 ,   6.3042874 ],
       ...,
       [ -0.11759591,   2.1230648 ,  -1.8058336 , ...,  -0.7617552 ,
         12.643952  ,  -0.83640176],
       [ -9.236514  ,   5.322989  ,  -5.334051  , ..., -11.693535  ,
         -0.35886312,   3.0221832 ],
       [  1.2127527 ,  -2.1050375 ,   1.8511745 , ...,  -3.7555826 ,
          8.241108  ,   0.07893485]], dtype=float32)

---
# Vanilla Transformer Block


In [19]:
class TransformerBlock(keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = keras.layers.MultiHeadAttention(num_heads=num_heads,
        key_dim=embed_dim)
        self.ffn = keras.Sequential(
        [keras.layers.Dense(ff_dim, activation="gelu"),
        keras.layers.Dense(embed_dim),]
        )
        self.layernorm1 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = keras.layers.Dropout(rate)
        self.dropout2 = keras.layers.Dropout(rate)
    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)

---
# Masked Transformer Block


In [20]:
class MaskedTransformerBlock(keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(MaskedTransformerBlock, self).__init__()
        self.att1 = keras.layers.MultiHeadAttention(num_heads=num_heads,
        key_dim=embed_dim)
        self.att2 = keras.layers.MultiHeadAttention(num_heads=num_heads,
        key_dim=embed_dim)
        self.ffn = keras.Sequential(
        [keras.layers.Dense(ff_dim, activation="gelu"),
        keras.layers.Dense(embed_dim),]
        )
        self.layernorm1 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm3 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = keras.layers.Dropout(rate)
        self.dropout2 = keras.layers.Dropout(rate)
        self.dropout3 = keras.layers.Dropout(rate)
    def causal_attention_mask(self, batch_size, n_dest, n_src, dtype):
        i = tf.range(n_dest)[:, None]
        j = tf.range(n_src)
        m = i >= j - n_src + n_dest
        mask = tf.cast(m, dtype)
        mask = tf.reshape(mask, [1, n_dest, n_src])
        mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
        )
        return tf.tile(mask, mult)
    def call(self, inputs, training):
        input_shape = tf.shape(inputs[0])
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        mask = self.causal_attention_mask(batch_size,
        seq_len, seq_len,
        tf.bool)
        attn_output1 = self.att1(inputs[0], inputs[0],
        attention_mask = mask)
        attn_output1 = self.dropout1(attn_output1, training=training)
        out1 = self.layernorm1(inputs[0] + attn_output1)
        attn_output2 = self.att2(out1, inputs[1])
        attn_output2 = self.dropout2(attn_output2, training=training)
        out2 = self.layernorm1(out1 + attn_output2)
        ffn_output = self.ffn(out2)
        ffn_output = self.dropout3(ffn_output, training=training)
        return self.layernorm2(out2 + ffn_output)

---
# Masked Position Embedding


In [21]:
class MaskedTokenAndPositionEmbedding(keras.layers.Layer):
    def __init__(self, maxlen, vocab_size, embed_dim, **kwargs):
        super(MaskedTokenAndPositionEmbedding, self).__init__(**kwargs)
        self.token_emb = keras.layers.Embedding(input_dim=vocab_size,
        output_dim=embed_dim,
        mask_zero=True)
        self.pos_emb = keras.layers.Embedding(input_dim=maxlen+1,
        output_dim=embed_dim,
        mask_zero=True)
    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=1, limit=maxlen+1, delta=1)
        positions = positions * tf.cast(tf.sign(x),tf.int32)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

---
# Custom Loss and Accuracy 


In [22]:
with strategy.scope():
    loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction='none')
def MaskedSparseCategoricalCrossentropy(real, pred):
    mask = tf.math.logical_not(tf.math.equal(real, 0))
    loss_ = loss_object(real, pred)
    mask = tf.cast(mask, dtype=loss_.dtype)
    loss_ *= mask
    return tf.reduce_sum(loss_)/tf.reduce_sum(mask)
def MaskedSparseCategoricalAccuracy(real, pred):
    accuracies = tf.equal(tf.cast(real,tf.int64), tf.argmax(pred, axis=2))
    mask = tf.math.logical_not(tf.math.equal(real, 0))
    accuracies = tf.math.logical_and(mask, accuracies)
    accuracies = tf.cast(accuracies, dtype=tf.float32)
    mask = tf.cast(mask, dtype=tf.float32)
    return tf.reduce_sum(accuracies)/tf.reduce_sum(mask)

---
# Setup

In [23]:
def clone_initializer(initializer):
    if isinstance(initializer, tf.keras.initializers.Initializer):
        return initializer.__class__.from_config(initializer.get_config())
    return initializer

In [141]:
def get_shape_list(tensor, expected_rank=None, name=None):
    if expected_rank is not None:
        assert_rank(tensor, expected_rank, name)

    shape = tensor.shape.as_list()

    non_static_indexes = []
    for (index, dim) in enumerate(shape):
        if dim is None:
            non_static_indexes.append(index)

    if not non_static_indexes:
        return shape

    dyn_shape = tf.shape(tensor)
    for index in non_static_indexes:
        shape[index] = dyn_shape[index]
    return shape

---
# Cache Memory

In [142]:
# current_state: `Tensor`, the current state.
# previous_state: `Tensor`, the previous state.
# memory_length: `int`, the number of tokens to cache.
# reuse_length: `int`, the number of tokens in the current batch to be cached
#     and reused in the future.
# Returns:  `Tensor`, representing the cached state with stopped gradients.
def _cache_memory(current_state, previous_state, memory_length, reuse_length=0):
    if memory_length is None or memory_length == 0:
        return None
    else:
        if reuse_length > 0:
            current_state = current_state[:, :reuse_length, :]

        if previous_state is None:
            new_mem = current_state[:, -memory_length:, :]
        else:
            new_mem = tf.concat(
                    [previous_state, current_state], 1)[:, -memory_length:, :]

    return tf.stop_gradient(new_mem)

---
# MultiHead Attention

In [168]:
# query: Query `Tensor` of shape `[B, T, dim]`.
# value: Value `Tensor` of shape `[B, S, dim]`.
# content_attention_bias: Bias `Tensor` for content based attention of shape
# `[num_heads, dim]`.
# positional_attention_bias: Bias `Tensor` for position based attention of
# shape `[num_heads, dim]`.
# key: Optional key `Tensor` of shape `[B, S, dim]`. If not given, will use
# `value` for both `key` and `value`, which is the most common case.
# relative_position_encoding: Relative positional encoding `Tensor` of shape
# `[B, L, dim]`.
# state: Optional `Tensor` of shape `[B, M, E]` where M is the length of the
# state or memory. If passed, this is also attended over as in Transformer
# XL.
# attention_mask: A boolean mask of shape `[B, T, S]` that prevents attention
# to certain positions.
class MultiHeadRelativeAttention(tf.keras.layers.MultiHeadAttention):
    def __init__(self,
                 kernel_initializer="variance_scaling",
                 **kwargs):
        super().__init__(kernel_initializer=kernel_initializer,
                                         **kwargs)

    def _build_from_signature(self, query, value, key=None):
        super(MultiHeadRelativeAttention, self)._build_from_signature(
                query=query,
                value=value,
                key=key)
        if hasattr(value, "shape"):
            value_shape = tf.TensorShape(value.shape)
        else:
            value_shape = value
        if key is None:
            key_shape = value_shape
        elif hasattr(key, "shape"):
            key_shape = tf.TensorShape(key.shape)
        else:
            key_shape = key

        common_kwargs = dict(
                kernel_initializer=self._kernel_initializer,
                bias_initializer=self._bias_initializer,
                kernel_regularizer=self._kernel_regularizer,
                bias_regularizer=self._bias_regularizer,
                activity_regularizer=self._activity_regularizer,
                kernel_constraint=self._kernel_constraint,
                bias_constraint=self._bias_constraint)

        with tf.init_scope():
            einsum_equation, _, output_rank = _build_proj_equation(
                    key_shape.rank - 1, bound_dims=1, output_dims=2)
            self._encoding_dense = tf.keras.layers.experimental.EinsumDense(
                    einsum_equation,
                    output_shape=_get_output_shape(
                        output_rank - 1,
                        [self._num_heads, self._key_dim]),
                        bias_axes=None,
                        name="encoding",
                        **common_kwargs)

# query: Projected query `Tensor` of shape `[B, T, N, key_dim]`.
# key: Projected key `Tensor` of shape `[B, S + M, N, key_dim]`.
# value: Projected value `Tensor` of shape `[B, S + M, N, key_dim]`.
# position: Projected position `Tensor` of shape `[B, L, N, key_dim]`.
# content_attention_bias: Trainable bias parameter added to the query head
#     when calculating the content-based attention score.
# positional_attention_bias: Trainable bias parameter added to the query
#     head when calculating the position-based attention score.
# attention_mask: (default None) Optional mask that is added to attention
#     logits. If state is not None, the mask source sequence dimension should
#     extend M.
# Returns:
# attention_output: Multi-headed output of attention computation of shape
#     `[B, S, N, key_dim]`.
    def compute_attention(
        self,
        query,
        key,
        value,
        position,
        content_attention_bias,
        positional_attention_bias,
        attention_mask=None
    ):
        #AC
        content_attention = tf.einsum(self._dot_product_equation, key, query + content_attention_bias)
        
        #positional_attention = tf.einsum(self._dot_product_equation, position, query + positional_attention_bias)
        
        #BD
       # positional_attention = _rel_shift(positional_attention, klen=tf.shape(content_attention)[3])
    
        positional_attention = None
        
        attention_sum = content_attention #+ positional_attention

        attention_scores = tf.multiply(attention_sum, 1.0 / math.sqrt(float(self._key_dim)))

        attention_scores = self._masked_softmax(attention_scores, attention_mask)

        attention_output = self._dropout_layer(attention_scores)

        attention_output = tf.einsum(self._combine_equation,
                                                                 attention_output,
                                                                 value)
        return attention_output

# * Number of heads (H): the number of attention heads.
# * Value size (V): the size of each value embedding per head.
# * Key size (K): the size of each key embedding per head. Equally, the size
#     of each query embedding per head. Typically K <= V.
# * Batch dimensions (B).
# * Query (target) attention axes shape (T).
# * Value (source) attention axes shape (S), the rank must match the target.
# * Encoding length (L): The relative positional encoding length.
# query: attention input.
# value: attention input.
# content_attention_bias: A trainable bias parameter added to the query head
#     when calculating the content-based attention score.
# positional_attention_bias: A trainable bias parameter added to the query
#     head when calculating the position-based attention score.
# key: attention input.
# relative_position_encoding: relative positional encoding for key and
#     value.
# state: (default None) optional state. If passed, this is also attended
#     over as in TransformerXL.
# attention_mask: (default None) Optional mask that is added to attention
#     logits. If state is not None, the mask source sequence dimension should
#     extend M.
# Returns:
# attention_output: The result of the computation, of shape [B, T, E],
#     where `T` is for target sequence shapes and `E` is the query input last
#     dimension if `output_shape` is `None`. Otherwise, the multi-head outputs
#     are projected to the shape specified by `output_shape`.
    def call(self,
             query,
             value,
             content_attention_bias,
             positional_attention_bias,
             key=None,
             relative_position_encoding=None,
             state=None,
             attention_mask=None):
        
        if not self._built_from_signature:
            self._build_from_signature(query, value, key=key)
        if key is None:
            key = value
        if state is not None and state.shape.ndims > 1:
            value = tf.concat([state, value], 1)
            key = tf.concat([state, key], 1)

        # `query` = [B, T, N ,H]
        query = self._query_dense(query)

        # `key` = [B, S + M, N, H]
        key = self._key_dense(key)

        # `value` = [B, S + M, N, H]
        value = self._value_dense(value)

        # # `position` = [B, L, N, H]
        # position = self._encoding_dense(relative_position_encoding)
        position = None
        
        
        attention_output = self.compute_attention(
                query=query,
                key=key,
                value=value,
                position=position,
                content_attention_bias=content_attention_bias,
                positional_attention_bias=positional_attention_bias,
                attention_mask=attention_mask)

        # `attention_output` = [B, S, N, H]
        attention_output = self._output_dense(attention_output)

        return attention_output

---
# Relative Shift

In [166]:
# def _rel_shift(x, klen=-1):    
#     x = tf.transpose(x, perm=[2, 3, 0, 1])
#     x = tf.pad(x, [[0, 0], [1, 0], [0, 0], [0, 0]])
#     x_size = tf.shape(x)
#     x = tf.reshape(x, [x_size[1], x_size[0], x_size[2], x_size[3]])
#     x = tf.slice(x, [1, 0, 0, 0], [-1, -1, -1, -1])
#     x = tf.reshape(x, [x_size[0], x_size[1] - 1, x_size[2], x_size[3]])
#     x = tf.transpose(x, perm=[2, 3, 0, 1])

#     return x

---
# Build Einsum Equation

In [151]:
_CHR_IDX = string.ascii_lowercase

# Builds an einsum equation for projections inside multi-head attention
def _build_proj_equation(free_dims, bound_dims, output_dims):
    input_str = ""
    kernel_str = ""
    output_str = ""
    bias_axes = ""
    letter_offset = 0
    for i in range(free_dims):
        char = _CHR_IDX[i + letter_offset]
        input_str += char
        output_str += char

    letter_offset += free_dims
    for i in range(bound_dims):
        char = _CHR_IDX[i + letter_offset]
        input_str += char
        kernel_str += char

    letter_offset += bound_dims
    for i in range(output_dims):
        char = _CHR_IDX[i + letter_offset]
        kernel_str += char
        output_str += char
        bias_axes += char
    equation = "%s,%s->%s" % (input_str, kernel_str, output_str)

    return equation, bias_axes, len(output_str)


def _get_output_shape(output_rank, known_last_dims):
    return [None] * (output_rank - len(known_last_dims)) + list(known_last_dims)

---
# Relative Position Embedding

In [152]:
# hidden_size: Size of the hidden layer.
# min_timescale: Minimum scale that will be applied at each position
# max_timescale: Maximum scale that will be applied at each position.
# class RelativePositionEmbedding(tf.keras.layers.Layer):

#     def __init__(self,
#                  hidden_size: int,
#                  min_timescale: float = 1.0,
#                  max_timescale: float = 1.0e4,
#                  **kwargs):
        
#         if "dtype" not in kwargs:
#             kwargs["dtype"] = "float32"

#         super().__init__(**kwargs)
#         self._hidden_size = hidden_size
#         self._min_timescale = min_timescale
#         self._max_timescale = max_timescale

#     def get_config(self):
#         config = {
#                 "hidden_size": self._hidden_size,
#                 "min_timescale": self._min_timescale,
#                 "max_timescale": self._max_timescale,
#         }
#         base_config = super(RelativePositionEmbedding, self).get_config()
#         return dict(list(base_config.items()) + list(config.items()))

# # inputs: An tensor whose second dimension will be used as `length`. If
# # `None`, the other `length` argument must be specified.
# # length: An optional integer specifying the number of positions. If both
# # `inputs` and `length` are spcified, `length` must be equal to the second
# # dimension of `inputs`.
# # Returns:
# # A tensor in shape of `(length, hidden_size)`.
#     def call(self, inputs, length=None):
#         if inputs is None and length is None:
#             raise ValueError("If inputs is None, `length` must be set in "
#                                              "RelativePositionEmbedding().")
#         if inputs is not None:
#             input_shape = get_shape_list(inputs)
#             if length is not None and length != input_shape[1]:
#                 raise ValueError(
#                         "If inputs is not None, `length` must equal to input_shape[1].")
#             length = input_shape[1]
#         position = tf.cast(tf.range(length), tf.float32)
#         num_timescales = self._hidden_size // 2
#         min_timescale, max_timescale = self._min_timescale, self._max_timescale
#         log_timescale_increment = (
#                 math.log(float(max_timescale) / float(min_timescale)) /
#                 (tf.cast(num_timescales, tf.float32) - 1))
#         inv_timescales = min_timescale * tf.exp(
#                 tf.cast(tf.range(num_timescales), tf.float32) *
#                 -log_timescale_increment)
#         scaled_time = tf.expand_dims(position, 1) * tf.expand_dims(
#                 inv_timescales, 0)
#         position_embeddings = tf.concat(
#                 [tf.sin(scaled_time), tf.cos(scaled_time)], axis=1)
#         position_embeddings = tf.expand_dims(position_embeddings, axis=0)
#         return tf.tile(position_embeddings, (tf.shape(inputs)[0], 1, 1))

In [153]:
# vocab_size: The size of the token vocabulary.
# hidden_size: The size of the transformer hidden layers.
# num_attention_heads: The number of attention heads.
# head_size: The dimension size of each attention head.
# inner_size: The inner size for the transformer layers.
# dropout_rate: Dropout rate for the output of this layer.
# attention_dropout_rate: Dropout rate on attention probabilities.
# norm_epsilon: Epsilon value to initialize normalization layers.
# inner_activation: The activation to use for the inner
#     FFN layers.
# kernel_initializer: Initializer for dense layer kernels.
# inner_dropout: Dropout probability for the inner dropoutlay er.
class TransformerXLBlock(tf.keras.layers.Layer):
    def __init__(self,
                 vocab_size,
                 hidden_size,
                 num_attention_heads,
                 head_size,
                 inner_size,
                 dropout_rate,
                 attention_dropout_rate,
                 norm_epsilon=1e-12,
                 inner_activation="relu",
                 kernel_initializer="variance_scaling",
                 inner_dropout=0.0,
                 **kwargs):
        """Initializes TransformerXLBlock layer."""

        super(TransformerXLBlock, self).__init__(**kwargs)
        self._vocab_size = vocab_size
        self._num_heads = num_attention_heads
        self._head_size = head_size
        self._hidden_size = hidden_size
        self._inner_size = inner_size
        self._dropout_rate = dropout_rate
        self._attention_dropout_rate = attention_dropout_rate
        self._inner_activation = inner_activation
        self._norm_epsilon = norm_epsilon
        self._kernel_initializer = kernel_initializer
        self._inner_dropout = inner_dropout
        self._attention_layer_type = MultiHeadRelativeAttention

    def build(self, input_shape):
        input_tensor = input_shape[0] if len(input_shape) == 2 else input_shape
        input_tensor_shape = tf.TensorShape(input_tensor)
        if len(input_tensor_shape.as_list()) != 3:
            raise ValueError("TransformerLayer expects a three-dimensional input of "
                                             "shape [batch, sequence, width].")
        batch_size, sequence_length, hidden_size = input_tensor_shape

        if len(input_shape) == 2:
            mask_tensor_shape = tf.TensorShape(input_shape[1])
            expected_mask_tensor_shape = tf.TensorShape(
                    [batch_size, sequence_length, sequence_length])
            if not expected_mask_tensor_shape.is_compatible_with(mask_tensor_shape):
                raise ValueError("When passing a mask tensor to TransformerXLBlock, "
                                                 "the mask tensor must be of shape [batch, "
                                                 "sequence_length, sequence_length] (here %s). Got a "
                                                 "mask tensor of shape %s." %
                                                 (expected_mask_tensor_shape, mask_tensor_shape))
        if hidden_size % self._num_heads != 0:
            raise ValueError(
                    "The input size (%d) is not a multiple of the number of attention "
                    "heads (%d)" % (hidden_size, self._num_heads))
        self._attention_layer = self._attention_layer_type(
                num_heads=self._num_heads,
                key_dim=self._head_size,
                value_dim=self._head_size,
                dropout=self._attention_dropout_rate,
                use_bias=False,
                kernel_initializer=clone_initializer(self._kernel_initializer),
                name="rel_attn")
        self._attention_dropout = tf.keras.layers.Dropout(
                rate=self._attention_dropout_rate)
        self._attention_layer_norm = tf.keras.layers.LayerNormalization(
                name="self_attention_layer_norm",
                axis=-1,
                epsilon=self._norm_epsilon,
                dtype=tf.float32)
        self._inner_dense = tf.keras.layers.experimental.EinsumDense(
                "abc,cd->abd",
                output_shape=(None, self._inner_size),
                bias_axes="d",
                kernel_initializer=clone_initializer(self._kernel_initializer),
                name="inner")

        self._inner_activation_layer = tf.keras.layers.Activation(
                self._inner_activation)
        self._inner_dropout_layer = tf.keras.layers.Dropout(
                rate=self._inner_dropout)
        self._output_dense = tf.keras.layers.experimental.EinsumDense(
                "abc,cd->abd",
                output_shape=(None, hidden_size),
                bias_axes="d",
                name="output",
                kernel_initializer=clone_initializer(self._kernel_initializer))
        self._output_dropout = tf.keras.layers.Dropout(rate=self._dropout_rate)
        self._output_layer_norm = tf.keras.layers.LayerNormalization(
                name="output_layer_norm",
                axis=-1,
                epsilon=self._norm_epsilon)

        
        super(TransformerXLBlock, self).build(input_shape)

    def get_config(self):
        config = {
                "vocab_size":
                        self._vocab_size,
                "hidden_size":
                        self._hidden_size,
                "num_attention_heads":
                        self._num_heads,
                "head_size":
                        self._head_size,
                "inner_size":
                        self._inner_size,
                "dropout_rate":
                        self._dropout_rate,
                "attention_dropout_rate":
                        self._attention_dropout_rate,
                "norm_epsilon":
                        self._norm_epsilon,
                "inner_activation":
                        self._inner_activation,
                "kernel_initializer":
                        self._kernel_initializer,
                "inner_dropout":
                        self._inner_dropout,
        }
        base_config = super(TransformerXLBlock, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

    
    # content_stream: `Tensor`, the input content stream. This is the standard
    # input to Transformer XL and is commonly referred to as `h` in XLNet.
    # content_attention_bias: Bias `Tensor` for content based attention of shape
    # `[num_heads, dim]`.
    # positional_attention_bias: Bias `Tensor` for position based attention of
    # shape `[num_heads, dim]`.
    # relative_position_encoding: Relative positional encoding `Tensor` of shape
    # `[B, L, dim]`.
    # state: Optional `Tensor` of shape `[B, M, E]`, where M is the length of
    # the state or memory. If passed, this is also attended over as in
    # Transformer XL.
    # content_attention_mask: Optional `Tensor` representing the mask that is
    # added to content attention logits. If state is not None, the mask source
    # sequence dimension should extend M.
    # query_attention_mask: Optional `Tensor` representing the mask that is
    # added to query attention logits. If state is not None, the mask source
    # sequence dimension should extend M.
    # target_mapping: Optional `Tensor` representing the target mapping when
    # calculating query attention.
    # Returns:
    # A `dict` object, containing the key value pairs for `content_attention`
    def call(self,
             content_stream,
             content_attention_bias,
             positional_attention_bias = None,
             relative_position_encoding=None,
             state=None,
             content_attention_mask=None,
             query_attention_mask=None,
             target_mapping=None):

        attention_kwargs = dict(
                query=content_stream,
                value=content_stream,
                key=content_stream,
                attention_mask=content_attention_mask)

        common_attention_kwargs = dict(
                content_attention_bias=content_attention_bias,
                relative_position_encoding=relative_position_encoding,
                positional_attention_bias=positional_attention_bias,
                state=state)

        attention_kwargs.update(common_attention_kwargs)
        attention_output = self._attention_layer(**attention_kwargs)

        attention_stream = attention_output
        input_stream = content_stream
        attention_key = "content_attention"
        attention_output = {}
        
        attention_stream = self._attention_dropout(attention_stream)
        attention_stream = self._attention_layer_norm(
                attention_stream + input_stream)
        inner_output = self._inner_dense(attention_stream)
        inner_output = self._inner_activation_layer(
                inner_output)
        inner_output = self._inner_dropout_layer(
                inner_output)
        layer_output = self._output_dense(inner_output)
        layer_output = self._output_dropout(layer_output)
        layer_output = self._output_layer_norm(layer_output + attention_stream)
        attention_output[attention_key] = layer_output

        return attention_output

---
# TransformerXL Layer

In [154]:
# vocab_size: The size of the token vocabulary.
# hidden_size: The size of the transformer hidden layers.
# num_attention_heads: The number of attention heads.
# head_size: The dimension size of each attention head.
# inner_size: The inner size for the transformer layers.
# dropout_rate: Dropout rate for the output of this layer.
# attention_dropout_rate: Dropout rate on attention probabilities.
# norm_epsilon: Epsilon value to initialize normalization layers.
# inner_activation: The activation to use for the inner
#     FFN layers.
# kernel_initializer: Initializer for dense layer kernels.
# inner_dropout: Dropout probability for the inner dropout
#     layer.
class TransformerXLBlock(tf.keras.layers.Layer):
    def __init__(self,
                 vocab_size,
                 hidden_size,
                 num_attention_heads,
                 head_size,
                 inner_size,
                 dropout_rate,
                 attention_dropout_rate,
                 norm_epsilon=1e-12,
                 inner_activation="relu",
                 kernel_initializer="variance_scaling",
                 inner_dropout=0.0,
                 **kwargs):
        """Initializes TransformerXLBlock layer."""

        super(TransformerXLBlock, self).__init__(**kwargs)
        self._vocab_size = vocab_size
        self._num_heads = num_attention_heads
        self._head_size = head_size
        self._hidden_size = hidden_size
        self._inner_size = inner_size
        self._dropout_rate = dropout_rate
        self._attention_dropout_rate = attention_dropout_rate
        self._inner_activation = inner_activation
        self._norm_epsilon = norm_epsilon
        self._kernel_initializer = kernel_initializer
        self._inner_dropout = inner_dropout
        self._attention_layer_type = MultiHeadRelativeAttention

    def build(self, input_shape):
        input_tensor = input_shape[0] if len(input_shape) == 2 else input_shape
        input_tensor_shape = tf.TensorShape(input_tensor)
        if len(input_tensor_shape.as_list()) != 3:
            raise ValueError("TransformerLayer expects a three-dimensional input of "
                                             "shape [batch, sequence, width].")
        batch_size, sequence_length, hidden_size = input_tensor_shape

        if len(input_shape) == 2:
            mask_tensor_shape = tf.TensorShape(input_shape[1])
            expected_mask_tensor_shape = tf.TensorShape(
                    [batch_size, sequence_length, sequence_length])
            if not expected_mask_tensor_shape.is_compatible_with(mask_tensor_shape):
                raise ValueError("When passing a mask tensor to TransformerXLBlock, "
                                                 "the mask tensor must be of shape [batch, "
                                                 "sequence_length, sequence_length] (here %s). Got a "
                                                 "mask tensor of shape %s." %
                                                 (expected_mask_tensor_shape, mask_tensor_shape))
        if hidden_size % self._num_heads != 0:
            raise ValueError(
                    "The input size (%d) is not a multiple of the number of attention "
                    "heads (%d)" % (hidden_size, self._num_heads))
        self._attention_layer = self._attention_layer_type(
                num_heads=self._num_heads,
                key_dim=self._head_size,
                value_dim=self._head_size,
                dropout=self._attention_dropout_rate,
                use_bias=False,
                kernel_initializer=clone_initializer(self._kernel_initializer),
                name="rel_attn")
        self._attention_dropout = tf.keras.layers.Dropout(
                rate=self._attention_dropout_rate)
        self._attention_layer_norm = tf.keras.layers.LayerNormalization(
                name="self_attention_layer_norm",
                axis=-1,
                epsilon=self._norm_epsilon,
                dtype=tf.float32)
        self._inner_dense = tf.keras.layers.experimental.EinsumDense(
                "abc,cd->abd",
                output_shape=(None, self._inner_size),
                bias_axes="d",
                kernel_initializer=clone_initializer(self._kernel_initializer),
                name="inner")

        self._inner_activation_layer = tf.keras.layers.Activation(
                self._inner_activation)
        self._inner_dropout_layer = tf.keras.layers.Dropout(
                rate=self._inner_dropout)
        self._output_dense = tf.keras.layers.experimental.EinsumDense(
                "abc,cd->abd",
                output_shape=(None, hidden_size),
                bias_axes="d",
                name="output",
                kernel_initializer=clone_initializer(self._kernel_initializer))
        self._output_dropout = tf.keras.layers.Dropout(rate=self._dropout_rate)
        self._output_layer_norm = tf.keras.layers.LayerNormalization(
                name="output_layer_norm",
                axis=-1,
                epsilon=self._norm_epsilon)

        super(TransformerXLBlock, self).build(input_shape)

    def get_config(self):
        config = {
                "vocab_size":
                        self._vocab_size,
                "hidden_size":
                        self._hidden_size,
                "num_attention_heads":
                        self._num_heads,
                "head_size":
                        self._head_size,
                "inner_size":
                        self._inner_size,
                "dropout_rate":
                        self._dropout_rate,
                "attention_dropout_rate":
                        self._attention_dropout_rate,
                "norm_epsilon":
                        self._norm_epsilon,
                "inner_activation":
                        self._inner_activation,
                "kernel_initializer":
                        self._kernel_initializer,
                "inner_dropout":
                        self._inner_dropout,
        }
        base_config = super(TransformerXLBlock, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

# content_stream: `Tensor`, the input content stream. This is the standard
# input to Transformer XL and is commonly referred to as `h` in XLNet.
# content_attention_bias: Bias `Tensor` for content based attention of shape
# `[num_heads, dim]`.
# positional_attention_bias: Bias `Tensor` for position based attention of
# shape `[num_heads, dim]`.
# relative_position_encoding: Relative positional encoding `Tensor` of shape
# `[B, L, dim]`.
# state: Optional `Tensor` of shape `[B, M, E]`, where M is the length of
# the state or memory. If passed, this is also attended over as in
# Transformer XL.
# content_attention_mask: Optional `Tensor` representing the mask that is
# added to content attention logits. If state is not None, the mask source
# sequence dimension should extend M.
# query_attention_mask: Optional `Tensor` representing the mask that is
# added to query attention logits. If state is not None, the mask source
# sequence dimension should extend M.
# target_mapping: Optional `Tensor` representing the target mapping when
# calculating query attention.
# Returns:
# A `dict` object, containing the key value pairs for `content_attention`
    def call(self,
             content_stream,
             content_attention_bias,
             positional_attention_bias,
             relative_position_encoding=None,
             state=None,
             content_attention_mask=None,
             query_attention_mask=None,
             target_mapping=None):
        
        attention_kwargs = dict(
                query=content_stream,
                value=content_stream,
                key=content_stream,
                attention_mask=content_attention_mask)

        common_attention_kwargs = dict(
                content_attention_bias=content_attention_bias,
                relative_position_encoding=relative_position_encoding,
                positional_attention_bias=positional_attention_bias,
                state=state)

        attention_kwargs.update(common_attention_kwargs)
        attention_output = self._attention_layer(**attention_kwargs)

        attention_stream = attention_output
        input_stream = content_stream
        attention_key = "content_attention"
        attention_output = {}
        
        attention_stream = self._attention_dropout(attention_stream)
        attention_stream = self._attention_layer_norm(attention_stream + input_stream)
        inner_output = self._inner_dense(attention_stream)
        inner_output = self._inner_activation_layer(
                inner_output)
        inner_output = self._inner_dropout_layer(
                inner_output)
        layer_output = self._output_dense(inner_output)
        layer_output = self._output_dropout(layer_output)
        layer_output = self._output_layer_norm(layer_output + attention_stream)
        attention_output[attention_key] = layer_output

        return attention_output

---
# TransformerXL

In [160]:
# num_layers: The number of layers.
# hidden_size: The hidden size.
# num_attention_heads: The number of attention heads.
# head_size: The dimension size of each attention head.
# inner_size: The hidden size in feed-forward layers.
# dropout_rate: Dropout rate used in each Transformer XL block.
# attention_dropout_rate: Dropout rate on attention probabilities.
# initializer: The initializer to use for attention biases.
# tie_attention_biases: Whether or not to tie biases together. If `True`, then
# each Transformer XL block shares the same trainable attention bias. If
# `False`, then each block has its own attention bias. This is usually set
# to `True`.
# memory_length: The number of tokens to cache.
# reuse_length: The number of tokens in the current batch to be cached
# and reused in the future.
# inner_activation: The activation to use in the inner layers
# for Transformer XL blocks. Typically "relu" or "gelu".
class TransformerXL(tf.keras.layers.Layer):
    def __init__(self,
                 vocab_size,
                 num_layers,
                 hidden_size,
                 maxlen,
                 embed_dim,
                 num_attention_heads,
                 head_size,
                 inner_size,
                 dropout_rate,
                 attention_dropout_rate,
                 initializer,
                 tie_attention_biases=True,
                 memory_length=None,
                 reuse_length=None,
                 inner_activation="relu",
                 **kwargs):
        super(TransformerXL, self).__init__(**kwargs)

        self._vocab_size = vocab_size
        self._initializer = initializer
        self._num_layers = num_layers
        self._hidden_size = hidden_size
        self._num_attention_heads = num_attention_heads
        self._head_size = head_size
        self._inner_size = inner_size
        self._inner_activation = inner_activation
        self._dropout_rate = dropout_rate
        self._attention_dropout_rate = attention_dropout_rate
        self._tie_attention_biases = tie_attention_biases

        self._memory_length = memory_length
        self._reuse_length = reuse_length

        if self._tie_attention_biases:
            attention_bias_shape = [self._num_attention_heads, self._head_size]
        else:
            attention_bias_shape = [self._num_layers, self._num_attention_heads, self._head_size]

        self.content_attention_bias = self.add_weight(
                "content_attention_bias",
                shape=attention_bias_shape,
                dtype=tf.float32,
                initializer=clone_initializer(self._initializer))
        # self.positional_attention_bias = self.add_weight(
        #         "positional_attention_bias",
        #         shape=attention_bias_shape,
        #         dtype=tf.float32,
        #         initializer=clone_initializer(self._initializer))

        self.transformer_xl_layers = []
        for i in range(self._num_layers):
            self.transformer_xl_layers.append(
                    TransformerXLBlock(
                            vocab_size=self._vocab_size,
                            hidden_size=self._head_size * self._num_attention_heads,
                            num_attention_heads=self._num_attention_heads,
                            head_size=self._head_size,
                            inner_size=self._inner_size,
                            dropout_rate=self._dropout_rate,
                            attention_dropout_rate=self._attention_dropout_rate,
                            norm_epsilon=1e-12,
                            inner_activation=self._inner_activation,
                            kernel_initializer="variance_scaling",
                            name="layer_%d" % i))

        self.output_dropout = tf.keras.layers.Dropout(rate=self._dropout_rate)

    def get_config(self):
        config = {
                "vocab_size":
                        self._vocab_size,
                "num_layers":
                        self._num_layers,
                "hidden_size":
                        self._hidden_size,
                "num_attention_heads":
                        self._num_attention_heads,
                "head_size":
                        self._head_size,
                "inner_size":
                        self._inner_size,
                "dropout_rate":
                        self._dropout_rate,
                "attention_dropout_rate":
                        self._attention_dropout_rate,
                "initializer":
                        self._initializer,
                "tie_attention_biases":
                        self._tie_attention_biases,
                "memory_length":
                        self._memory_length,
                "reuse_length":
                        self._reuse_length,
                "inner_activation":
                        self._inner_activation,
        }
        base_config = super(TransformerXL, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

# content_stream: `Tensor`, the input content stream. This is the standard
# input to Transformer XL and is commonly referred to as `h` in XLNet.
# relative_position_encoding: Relative positional encoding `Tensor` of shape
# `[B, L, dim]`.
# state: Optional `Tensor` of shape `[B, M, E]`, where M is the length of
# the state or memory. If passed, this is also attended over as in
# Transformer XL.
# content_attention_mask: Optional `Tensor` representing the mask that is
# added to content attention logits. If state is not None, the mask source
# sequence dimension should extend M.
# query_attention_mask: Optional `Tensor` representing the mask that is
# added to query attention logits. If state is not None, the mask source
# sequence dimension should extend M.
# target_mapping: Optional `Tensor` representing the target mapping when
# calculating query attention.
# Returns:
# A tuple consisting of the attention output and the list of cached memory
# states.
# The attention output is `content_attention`
    def call(self,
             content_stream,
             relative_position_encoding,
             state=None,
             content_attention_mask=None,
             query_attention_mask=None,
             target_mapping=None):
        
        new_mems = []

        if state is None:
            state = [None] * self._num_layers
        for i in range(self._num_layers):
            # cache new mems
            new_mems.append(
                    _cache_memory(content_stream, state[i],
                                                self._memory_length, self._reuse_length))
            
            if self._tie_attention_biases:
                content_attention_bias = self.content_attention_bias
            else:
                content_attention_bias = self.content_attention_bias[i]
                
            # if self._tie_attention_biases:
            #     positional_attention_bias = self.positional_attention_bias
            # else:
            #     positional_attention_bias = self.positional_attention_bias[i]
            positional_attention_bias = None
            

            transformer_xl_layer = self.transformer_xl_layers[i]
            
            transformer_xl_output = transformer_xl_layer(
                    content_stream=content_stream,
                    content_attention_bias=content_attention_bias,
                    positional_attention_bias=positional_attention_bias,
                    relative_position_encoding=relative_position_encoding,
                    state=state[i],
                    content_attention_mask=content_attention_mask,
                    query_attention_mask=query_attention_mask,
                    target_mapping=target_mapping)
            content_stream = transformer_xl_output["content_attention"]

        output_stream = content_stream
        return output_stream, new_mems

---
# Dna Embeddings Model

In [161]:
class Dna_Embeddings_Model(keras.Model):
    def __init__(self, seq_len, encoder, embed_dim):
        super(Dna_Embeddings_Model, self).__init__()
        
        self.seq_len = seq_len
        self.encoder = encoder
        self.embed_dim = embed_dim
        
        # self.input_layer = keras.layers.Input((None,seq_len))
        # self.time_distributed_layer = keras.layers.TimeDistributed(encoder)
        # self.dense_layer = keras.layers.Dense(embed_dim)
    
    def call(self, dataset, training=None):
#         input_embeddings = self.input_layer
#         distributed_embeddings = self.time_distributed_layer(input_embeddings)
#         output_embeddings = self.dense_layer(distributed_embeddings)
        
#         model = keras.Model(input_embeddings, output_embeddings)
              
#         return model
        return None
    
    def create_model(self):
        input_layer = keras.layers.Input((None, self.seq_len))
        time_distributed_layer = keras.layers.TimeDistributed(self.encoder)(input_layer)
        dense_layer = keras.layers.Dense(self.embed_dim)(time_distributed_layer)
        
        model = keras.Model(input_layer, dense_layer)
        
        return model        

In [162]:
#Hyper Parameters 
seq_len = 148
encoder = pretrained_encoder
embed_dim = 32

---
# Test DNA Model

In [177]:
with strategy.scope():  
    dna_model = Dna_Embeddings_Model(seq_len, encoder, embed_dim)
    dna_model = dna_model.create_model()
    #dna_model.compile(optimizer=keras.optimizers.Adam(1e-4),loss=keras.losses.SparseCategoricalCrossentropy(from_logits = True), metrics = [keras.metrics.sparse_categorical_accuracy])
    
    
    batch = dataset[0][0]
    batch_size = dataset[0][0][0].shape
    dna_embeddings = dna_model(batch)

In [178]:
dna_embeddings.shape

TensorShape([20, 700, 32])

In [179]:
dna_embeddings

<tf.Tensor: shape=(20, 700, 32), dtype=float32, numpy=
array([[[-3.9879537 ,  3.8753116 ,  3.8554542 , ...,  1.5293021 ,
         -1.8139416 , -1.2552106 ],
        [ 1.4834095 , -0.09260456,  0.46363428, ...,  3.49958   ,
         -1.0442907 , -0.04607025],
        [ 2.9982667 , -0.34751317, -1.2545336 , ...,  5.6417484 ,
          1.8454205 , -0.64657986],
        ...,
        [ 1.6055295 ,  7.0958934 ,  7.257243  , ..., -3.9404395 ,
          0.13447534,  8.348375  ],
        [ 1.8501576 , -0.2726029 , -1.7018017 , ...,  6.220066  ,
         -2.2616332 ,  0.34388867],
        [ 3.6608975 ,  2.162143  ,  3.5645483 , ..., -4.9542446 ,
         -0.6773416 ,  6.498264  ]],

       [[ 4.423611  , -2.212044  , -3.5878837 , ...,  8.262689  ,
         -0.76589817, -3.2996655 ],
        [ 6.5634246 , -4.7361717 , -5.228298  , ...,  8.327922  ,
         -7.438349  , -1.7114404 ],
        [ 3.6485624 , -2.8724189 , -3.4627936 , ...,  7.11956   ,
         -1.9525318 , -3.7502909 ],
        ...,

---
# XL Model

In [173]:
class XlModel(keras.Model):
    def __init__(self, output_shape, embed_dim, num_layers, hidden_size, num_attention_heads, maxlen, memory_length, reuse_length, 
                                        head_size, inner_size, dropout_rate, attention_dropout_rate, initializer, vocab_size = None):
        super(XlModel, self).__init__()
        
        self.embed_dim = embed_dim
        self.num_heads = num_attention_heads
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.maxlen = maxlen
        self.memory_length = memory_length
        
        self.transformer_xl = TransformerXL(
                vocab_size=vocab_size,
                num_layers=num_layers,
                hidden_size=hidden_size,
                num_attention_heads=num_attention_heads,
                maxlen=maxlen,
                embed_dim=embed_dim,
                memory_length=memory_length,
                reuse_length=reuse_length,
                head_size=head_size,
                inner_size=inner_size,
                dropout_rate=dropout_rate,
                attention_dropout_rate=attention_dropout_rate,
                initializer=initializer
            )
  
        self.pooling_layer = stf.PoolingByMultiHeadAttention(num_seeds=1,embed_dim=embed_dim,num_heads=1,use_layernorm=use_layernorm,pre_layernorm=pre_layernorm,
                                                 use_keras_mha=use_keras_mha,is_final_block=True)

        self.output_layer = keras.layers.Dense(output_shape, activation=keras.activations.sigmoid)


    def call(self, x, mems, training=None):       
      
        encoder, mems = self.transformer_xl(content_stream=x, relative_position_encoding=None, state=mems)
        
        pooled = self.pooling_layer(encoder)
    
        classification = self.output_layer(pooled)
        
        return classification, mems

In [190]:
#Hyper Parameters 
output_shape = max_files
embed_dim = 32
num_layers = 12
hidden_size = 64
num_attention_heads = 8
maxlen = seq_len
memory_length = 0
reuse_length = 0
head_size = 64
inner_size = 64
dropout_rate = 0.0
attention_dropout_rate = 0.0
initializer = keras.initializers.RandomNormal(stddev=0.1) 
vocab_size = None

---
# Create DNA XL Model

In [191]:
with strategy.scope():  
    #Dna Model 
    dna_model = Dna_Embeddings_Model(seq_len, encoder, embed_dim)
    dna_model = dna_model.create_model()
    #dna_model.compile(optimizer=keras.optimizers.Adam(1e-4),loss=keras.losses.SparseCategoricalCrossentropy(from_logits = True), metrics = [keras.metrics.sparse_categorical_accuracy])

    batch_dna = dataset[0][0]
    dna_embeddings = dna_model(batch_dna)
    
    #XL Model
    model = XlModel(output_shape, embed_dim, num_layers, hidden_size, num_attention_heads, maxlen, memory_length, reuse_length, head_size, inner_size, dropout_rate, attention_dropout_rate, initializer, vocab_size = None)
    model.compile(loss = keras.losses.CategoricalCrossentropy , optimizer = keras.optimizers.Adam())
    
    batch_xl = dna_embeddings
    batch_size = dataset[0][0].shape[0] #20
    
    mems = [*tf.zeros((num_layers, batch_size, memory_length, embed_dim))]
    
    output, mems = model(dna_embeddings, mems)
    
    tf.print(output)

[[[0.433057249 0.556360364 0.579769313 ... 0.604828954 0.637039959 0.519640565]]

 [[0.511237621 0.497999549 0.613589764 ... 0.58514446 0.58947593 0.536577106]]

 [[0.434808761 0.554745793 0.580063283 ... 0.60638392 0.63962239 0.51991272]]

 ...

 [[0.43073225 0.554157257 0.580819607 ... 0.606903076 0.640633702 0.519960403]]

 [[0.518595695 0.493677795 0.604711652 ... 0.582517385 0.578340471 0.539728761]]

 [[0.430938661 0.554437518 0.57796979 ... 0.605135798 0.638500571 0.520724714]]]


In [194]:
output.shape

TensorShape([20, 1, 1260])

In [185]:
dataset[0][0][0][0]

array([30., 27., 11., 56., 32., 36., 56., 32., 36., 57., 37., 63., 65.,
       75.,  3., 15., 76.,  7., 38., 65., 77., 12., 63., 67., 87., 61.,
       55., 25.,  2., 11., 57., 38., 68., 92., 88., 66., 81., 32., 37.,
       60., 53., 18., 93., 90., 75.,  3., 17., 87., 62., 61., 57., 38.,
       65., 75.,  0.,  2., 10., 52., 11., 57., 36., 57., 36., 55., 27.,
       12., 61., 57., 37., 63., 66., 82., 38., 68., 91., 80., 25.,  2.,
       13., 66., 82., 36., 57., 38., 67., 88., 67., 85., 50.,  0.,  2.,
       11., 56., 31., 31., 31., 32., 37., 61., 58., 41., 80., 25.,  1.,
        8., 42., 87., 62., 62., 60., 52., 12., 62., 63., 66., 80., 26.,
        7., 36., 57., 35., 53., 15., 76.,  8., 42., 85., 53., 16., 82.,
       35., 51.,  8., 41., 82., 35., 50.,  2., 12., 61., 55., 27., 12.,
       60., 52., 10., 52., 12.])

In [208]:
dataset[0][1]

array([127,  77, 163,  41,  77,  40, 101, 134, 162,  81, 143, 117,  99,
       190,  54, 188, 131, 155,  19, 159], dtype=int32)

In [223]:
output[0][0]

<tf.Tensor: shape=(1260,), dtype=float32, numpy=
array([0.43305725, 0.55636036, 0.5797693 , ..., 0.60482895, 0.63703996,
       0.51964056], dtype=float32)>

In [210]:
print('Max:', np.amax(output[0][0]))
print(np.where(output[0][0] == np.amax(output[0][0])))

Max: 0.67633617
(array([771]),)


In [211]:
model.summary()

Model: "xl_model_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 transformer_xl_18 (Transfor  multiple                 838784    
 merXL)                                                          
                                                                 
 pooling_by_multi_head_atten  multiple                 5312      
 tion_18 (PoolingByMultiHead                                     
 Attention)                                                      
                                                                 
 dense_168 (Dense)           multiple                  41580     
                                                                 
Total params: 885,676
Trainable params: 885,676
Non-trainable params: 0
_________________________________________________________________


---
# Custom Train Step

In [ ]:
def train_step(batch, mems):
    x, y = batch
    
    with tf.GradientTape() as tape:
        result, new_mems = model(x, mems, y, training=True)
        loss = MaskedSparseCategoricalCrossentropy(y_post, result)
        
    accuracy = keras.metrics(SparseCategoricalAccuracy(y, result)
        
    grads = tape.gradient(loss, model.trainable_weights)
    model.optimizer.apply_gradients(zip(grads, model.trainable_weights))
    return loss, accuracy, new_mems

@tf.function()
def dist_train_step(batch, mems):
    losses, accuracy, new_mems = strategy.run(train_step, args=(batch, mems))
    return strategy.reduce(tf.distribute.ReduceOp.SUM, losses, axis=None), accuracy, new_mems

In [165]:
#Hyperparameters
history_loss = []
history_accuracy = []
epochs = 50

In [ ]:
with strategy.scope():    
    for epoch in range(epochs):
        batch = (x_train, pre_y_train, post_y_train)

        loss, accuracy, mems = dist_train_step(batch, mems)
        
        history_loss.append(loss)
        history_accuracy.append(accuracy) 
        
        print(f"\r{epoch+1}/{epochs} Loss: {loss} Accuracy = {accuracy}", end="")

133/200 Loss: 0.42261186242103577 Accuracy = 0.9020711183547974

In [ ]:
plt.figure(1)
plt.subplot(211)
plt.plot(history_accuracy)
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.subplot(212)
plt.plot(history_loss)
plt.ylabel('Loss')
plt.xlabel('Epoch')